### PR TITLE
Use dirname(@__FILE__) instead of Pkg.dir

### PR DESCRIPTION
**Pull request by tkelman**
this allows installing and loading the package from elsewhere on LOAD_PATH

### CODE REVIEW

**Comment by juliohm** [comment]
Hi @tkelman, shouldn't `Pkg.dir("PkgName")` handle it instead?

**Comment by tkelman** [comment]
`Pkg.dir` only loads from the package directory. Packages can be placed elsewhere though. If you add a directory to `LOAD_PATH` then you can do `using Foo`, but the package won't be located in `Pkg.dir`. This is the case on JuliaBox, and other use cases. See https://github.com/JuliaLang/julia/issues/12120 and https://github.com/JuliaLang/julia/issues/8679.

**Comment by juliohm** [comment]
What I mean is `Pkg.dir("PkgName") shouldn't always return the correct directory regardless of where the package is in `LOAD_PATH`? I see why `Pkg.dir()` without arguments should not work.

**Comment by tkelman** [comment]
That's not how `Pkg.dir("PkgName")` works right now, no. Whatever replaces it should hopefully fix that problem, but for now it's incorrect for a package to refer to its own location in that way. It's only really suitable for interactive use or one-off scripts that aren't part of a package.

**Comment by juliohm** [comment]
Is there an issue in Julia already tracking this Pkg.dir() detail? Merging this, thanks.

**Comment by tkelman** [comment]
The two that I linked above.

**Pull request merged**
